language: node_js
sudo: true
node_js:
  - "node"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

script: npm run test:chrome -- --browsers ChromeNoSandbox

after_success:
  cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js